import {
    Bell,
    BriefcaseBusiness,
    Building2,
    Bot,
    BrainCircuit,
    ChartNoAxesCombined,
    Check,
    ClipboardCheck,
    ClipboardList,
    Download,
    Eye,
    FileText,
    History,
    Lightbulb,
    ListChecks,
    LogOut,
    MessageSquare,
    Pencil,
    Plus,
    Search,
    Send,
    Settings,
    Sparkles,
    Target,
    Trash2,
    Upload,
    UserRound,
    Users,
    Video,
    X,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    CircleCheck,
    CircleX,
    Clock3,
    Filter,
    Mail,
    LockKeyhole,
    KeyRound,
    BarChart3,
    FileSearch,
    ScanSearch,
    Rocket,
    Save,
    Trophy,
    PartyPopper,
    Info,
    CircleUserRound,
    Circle,
    MapPin,
    Globe2,
    Tag,
    Brain,
    BookOpen,
    Code2,
    CalendarDays,
    MailCheck,
    Zap,
    Dumbbell,
    Sun,
    Moon,
} from 'lucide-react';

const ICONS = {
    bell: Bell,
    briefcase: BriefcaseBusiness,
    building: Building2,
    bot: Bot,
    brain: BrainCircuit,
    analytics: ChartNoAxesCombined,
    check: Check,
    clipboardCheck: ClipboardCheck,
    clipboard: ClipboardList,
    download: Download,
    eye: Eye,
    file: FileText,
    history: History,
    idea: Lightbulb,
    list: ListChecks,
    logout: LogOut,
    message: MessageSquare,
    edit: Pencil,
    plus: Plus,
    search: Search,
    send: Send,
    settings: Settings,
    sparkles: Sparkles,
    target: Target,
    delete: Trash2,
    upload: Upload,
    user: UserRound,
    users: Users,
    interview: Video,
    close: X,
    warning: AlertTriangle,
    down: ArrowDown,
    left: ArrowLeft,
    right: ArrowRight,
    success: CircleCheck,
    error: CircleX,
    clock: Clock3,
    filter: Filter,
    mail: Mail,
    lock: LockKeyhole,
    key: KeyRound,
    chart: BarChart3,
    fileSearch: FileSearch,
    scan: ScanSearch,
    rocket: Rocket,
    save: Save,
    trophy: Trophy,
    celebration: PartyPopper,
    info: Info,
    candidate: CircleUserRound,
    circle: Circle,
    pin: MapPin,
    globe: Globe2,
    tag: Tag,
    brainTopic: Brain,
    book: BookOpen,
    code: Code2,
    calendar: CalendarDays,
    email: MailCheck,
    lightning: Zap,
    strength: Dumbbell,
    sun: Sun,
    moon: Moon,
    home: Building2,
};

function Icon({ name, size = 18, strokeWidth = 1.9, className = '' }) {
    const IconComponent = ICONS[name] || Circle;

    return (
        <IconComponent
            size={size}
            strokeWidth={strokeWidth}
            className={`app-icon ${className}`.trim()}
            aria-hidden="true"
        />
    );
}

export default Icon;